---
- name: Gather package facts
  package_facts:
    manager: auto

- name: Ensure mandatory variables are defined
  assert:
    that:
      - '{{ item }} is defined'
      - '{{ item }} != None'
    fail_msg: '{{ item }} must be set before executing role'
  loop:
    - target_user_name
    - with_ssl
    - haproxy_services

- name: Install packages
  package:
    name:
      - haproxy
    state: latest
    update_cache: yes
  when: "'haproxy' not in ansible_facts.packages"

# In case closed
- name: Allow tcp 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Configure SSL if desired
  include_tasks: configure_ssl.yaml
  when: with_ssl == true

- name: Populate haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Reload haproxy service
  systemd:
    name: haproxy
    state: restarted
