---
- name: Ensure mandatory variables are defined
  assert:
    that:
      - '{{ item }} is defined'
      - '{{ item }} != None'
    fail_msg: '{{ item }} must be set before executing role'
  loop:
    - target_domain
    - certificate_email

- name: Install packages
  package:
    name:
      - snapd
    state: latest
    update_cache: yes

- name: Install snap core
  snap:
    name: core

- name: Install certbot
  snap:
    name: certbot
    classic: true

- name: Symlink for better results
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Allow default tcp 80
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 80
    - 443

- name: Generate new certificate
  command: certbot certonly --standalone --noninteractive --agree-tos --email {{ certificate_email }} -d {{ target_domain }}
  args:
    creates: /etc/letsencrypt/live/{{ target_domain }}
