---
- name: Fail if target user is root
  fail:
    msg: Ansible must not be installed as root user; retry with a different target_user_name
  when: target_user_name == 'root'

- name: Install deps
  package:
    name:
      - python3-distutils
    state: latest
    update_cache: yes

- name: Install via python3
  command: python3 -m pip install --user ansible
  become: true
  become_user: '{{ target_user_name }}'
