---
- name: Create node_exporter user group
  group:
    name: '{{ node_exporter_group }}'
    state: present
    system: true

- name: Create node_exporter user
  user:
    name: '{{ node_exporter_user }}'
    groups: '{{ node_exporter_group }}'
    append: true
    system: yes
    createhome: false
    shell: /usr/sbin/nologin
    home: /

- name: Get Node Exporter package
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Relocate executable
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter
    dest: /usr/local/bin
    owner: '{{ node_exporter_user }}'
    group: '{{ node_exporter_group }}'
    remote_src: yes
    mode: 0755

- name: Write node_exporter service file
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Start node_exporter service
  service:
    name: node_exporter
    state: restarted
    enabled: yes

- name: Ensure node exporter returns metrics
  uri:
    url: http://localhost:9100/metrics
    method: GET
    status_code: 200
