---
- name: Update kernel
  include_tasks: 'update_kernel.yaml'
  when: ansible_facts.kernel == default_contabo_kernel

- name: Install packages
  package:
    name:
      - build-essential
      - zsh
      - git 
      - python3-pip
      - screen
      - jq
      - lolcat
    state: latest
    update_cache: yes
      
- name: Make zsh default
  shell: chsh -s /bin/zsh

- name: Configure new user
  include_tasks: user.yaml
  when: target_user_name != 'root'

- name: Configure root user
  include_tasks: root.yaml
  when: target_user_name == 'root'

- name: Get n(ode) install file
  get_url: 
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /tmp/n
    mode: 0755

- name: Install n(ode)
  shell: /tmp/n current

- name: Cleanup n(ode) install file
  file:
    path: /tmp/n
    state: absent

- name: Disallow login via password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes$'
    line: 'PasswordAuthentication no'
    backrefs: yes

- name: Allow login via key only
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication yes$'
    line: 'PubkeyAuthentication yes'
    backrefs: yes

- name: Increase SSH timeout
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#ClientAliveInterval 0$'
    line: ClientAliveInterval 3600
    backrefs: yes

- name: Restart sshd service 
  systemd:
    name: sshd
    state: restarted

- name: Update firewall settings
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  ufw:
    state: enabled
