- name: Authorize new public key
  authorized_key:
    user: '{{ target_user_name }}'
    state: present
    key: "{{ lookup('file', '~/.ssh/id_c3s.pub') }}"

- name: Write dotfiles to home
  copy:
    src: '{{ item }}'
    dest: ~/
  loop:
    - .alias
    - .motd
    - .zsh_plugins.list
    - .hushlogin
    - .oh-my-zsh-install.sh

# XXX: use async because Ansible hangs otherwise
- name: Install oh-my-zsh
  shell: sh ~/.oh-my-zsh-install.sh
  args:
    creates: ~/.oh-my-zsh
  async: 10

- name: Install antidote
  shell: git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
  args:
    creates: ~/.antidote

- name: Write .zshrc to new user's home dir
  copy:
    src: .zshrc
    dest: ~/
