- name: Move files to .bash_files directory
  command: mv /etc/skel/.bash_logout /etc/skel/.bashrc /etc/skel/.profile /etc/skel/.bash_files
  creates: /etc/skel/.bash_files

- name: Write dotfiles to skel
  copy:
    src: "{{ item }}"
    dest: /etc/skel
  loop:
    - .alias
    - .motd
    - .zsh_plugins.list
    - .hushlogin

- name: Add new user
  user:
    name: "{{ target_user_name }}"
    shell: /bin/zsh
    password: "{{ target_user_pass }}"
    groups: sudo

- name: Authorize new user public key
  authorized_key:
    user: "{{ target_user_name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_c3s.pub') }}"

- block:
  - name: Write .oh-my-zsh-install.sh to home
    copy:
      src: .oh-my-zsh-install.sh
      dest: ~/

  - name: Install oh-my-zsh
    command: sh ~/.oh-my-zsh-install.sh
    creates: ~/.oh-my-zsh

  - name: Install antidote
    command: git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
    creates: ~/.antidote

  - name: Write .zshrc to new user's home dir
    copy:
      src: .zshrc
      dest: ~/
  become: true
  become_user: "{{ target_user_name }}"

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes$'
    line: 'PermitRootLogin no'
    backrefs: yes
