---
- name: Get skel contents
  find:
    paths: /etc/skel
    patterns: '*'
    hidden: yes
  register: skell_dir

- name: Remove skel contents
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ skell_dir.files }}'

- name: Write dotfiles to skel
  copy:
    src: '{{ item }}'
    dest: /etc/skel
  loop:
    - .alias
    - .motd
    - .zsh_plugins.list
    - .hushlogin
    - .oh-my-zsh-install.sh

- name: Add new user
  user:
    name: '{{ target_user_name }}'
    shell: /bin/zsh
    password: '{{ target_user_pass }}'
    groups: sudo

- name: Authorize new user public key
  authorized_key:
    user: '{{ target_user_name }}'
    state: present
    key: "{{ lookup('file', '~/.ssh/id_c3s.pub') }}"

- block:
    - name: Install oh-my-zsh
      command: sh ~/.oh-my-zsh-install.sh
      args:
        creates: ~/.oh-my-zsh

    - name: Install antidote
      command: git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
      args:
        creates: ~/.antidote

    - name: Write .zshrc to new user's home dir
      copy:
        src: .zshrc
        dest: ~/
  become: true
  become_user: '{{ target_user_name }}'

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes$'
    line: 'PermitRootLogin no'
    backrefs: yes
